### ISSUE TITLE
About APPID

### ISSUE THREAD

**Issue by ghost** [swim2sun/hass-config-milo#2]
Hello,

I'm the technical staff of CoolKit eWeLink, how did you get our APPID and APP Secret?

**Comment by swim2sun** [comment]
@coolkit-carl 我用的这个插件 https://github.com/AlexxIT/SonoffLAN 。
另外，我用的你们的单火线开关，灯开着的时候经常无缘无故就自动关了...你知道是什么原因吗？😂

**Comment by ghost** [comment]
> @coolkit-carl 我用的这个插件 https://github.com/AlexxIT/SonoffLAN 。
> 另外，我用的你们的单火线开关，灯开着的时候经常无缘无故就自动关了...你知道是什么原因吗？😂

自动关闭，得看是什么产品，你用我们易微联的APP，也会出现这样的情况吗？如果也一样，那松诺设备的话可以直接找到他们的售后。

要么是硬件的电路问题，要么就是固件Bug。

**Comment by swim2sun** [comment]
@coolkit-carl 用易微联和物理开关都有这样的问题，我后面升级下固件试试吧，谢谢

**Comment by ghost** [comment]
> @coolkit-carl 用易微联和物理开关都有这样的问题，我后面升级下固件试试吧，谢谢

可以
